micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/bootdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    entity-scan:
      packages: com.example.entity